### ISSUE TITLE
when choose option from select dropdown, other tab does not select the same option(does not select anything at all)

### ISSUE THREAD

**Issue by MursalRepo** [Oppodelldog/chrome-extension-mirror#3] opened 2020-10-12 14:03 UTC
Firstly, this extention is great and idea is cool, but needs some improvement, as i said in the header, choosing one option in select dropdown, does not affect the other tab. is it possible to fix this? thank you

**Comment by MursalRepo** [comment] 2020-10-13 14:27
Thank you for your quick reply!
yes you are right in some dropdowns it is working, but in the website there is one specific dropdown (actually is same with others) that is non responsive, I am adding the class here:
`
<div class="fld">
  <label for="tramiteGrupo[1]">TRÁMITES ...</label>
  <select name="tramiteGrupo[1]" id="tramiteGrupo[1]" onchange="eliminarSeleccionOtrosGrupos(1)" class="mf-input__l">
  <option value='-1'>Despliegue para ver trámites disponibles en esta provincia</option>
  <option value='4036'>OP1</option>
  <option value='4067'>OP2</option>
  <option value='4010'>OP_N</option>
  </select>
  </div>
`
is just regular dropdown options but for some reason, changing this dropdown in this tab does not affect other tabs

**Comment by Oppodelldog** [comment] 2020-10-15 21:13
@MursalRepo I took a look and can confirm this html works so far.
One thing that is missing in your sample is the implementation of the onchange callback **eliminarSeleccionOtrosGrupos**

So by just implementing en empty function this sample works.

But if this function would make a call to
 ```javascript 
e.stopPropagation()
```
the error can be reproduced since event propagation is stopped, so the extensions event callback is not triggered.
So far for reproduction. Could you take a look at the real implementation to confirm we are talking about the same issue here?

If you have any idea how to fix this it's appreciated. This is anyway a valid enhancement.

**Comment by MursalRepo** [comment] 2020-10-16 09:26
ok you are right. so we can say that this is a small defect in the production page itself. we may close this issue now.
thank you!

**Comment by Oppodelldog** [comment] 2020-10-16 14:06
I would not say the production page has a defect. The chrome extension should be able to handle those situations - which might be a bit tricky without changing the tested websites behavior, the site will have a good reason to stop propagation.
So I would keep this issue open as a general enhancement of the extension.

**Comment by Oppodelldog** [comment] 2020-10-17 12:22
@MursalRepo This should be fixed now, in my test pages this works now. 
So relying on the assumption the change event in your use case was also stopped by stopPropagation, this  now.hould work now for you.

**Closed** 2021-10-15 17:44 UTC
Labels: enhancement
